services:
  postgres:
    image: postgres:16
    command: postgres -c superuser_reserved_connections=1 -c max_connections=3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
